### ISSUE TITLE
Метод post wall не отправляет длинные сообщения

### ISSUE THREAD

**Issue by timofeyp** [wolframdeus/vk-api#5]
Если сообщение примерно 1000+ символов, ошибка запроса.

Вызывал через addRequestToQueue

**Comment by wolframdeus** [comment]
Покажите пожалуйста как вызываете метод и с какими параметрами

**Comment by wolframdeus** [comment]
На своей стороне попробовал такой вариант:

```
const api = new VKAPI({
  accessToken: '...',
  rps: 1,
  v: '5.130',
  isBrowser: true,
});

const message = new Array(2000).fill('a').join('');

api.addRequestToQueue({
  method: 'wall.post',
  params: {
    ownerId: ...,
    message,
  }
}).then(console.log)
  .catch(console.log)
```

Проблему воспроизвести не смог

**Comment by wolframdeus** [comment]
Закрыто ввиду отсутствия активности. Пожалуйста, переоткройте issue в случае, если проблема воспроизводится и приведите минимальный пример с котором стабильно воспроизводится проблема.

Предположительно, проблема на клиентской стороне и связана с подключением к Интернету.
